version: "3.8"

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    container_name: my-node-app
    restart: unless-stopped
    volumes:
      - .:/container
      - node_modules:/container/node_modules
    ports:
      - "2001:2000"
    networks:
      - app-network
    # command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: